version: "3.9"
services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_PASSWORD: password
      MYSQL_USER: mysql_user
      MYSQL_DATABASE: mysql_database
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - /var/lib/mysql
    networks:
      - internal
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
  api:
    image: $IMAGE_TAG_APP
    user: "1000:1000"
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_DATABASE: mysql_database
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_CONNECTION: mysql
      LOG_CHANNEL: stderr
      APP_NAME: $APP_NAME
      APP_URL: https://$APP_URL
      ASSET_URL: https://$APP_URL

    networks:
      - internal
    volumes:
      - public_link:/var/www/html/public

  web:
    image: $IMAGE_TAG_WEB
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - internal
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${CI_PROJECT_ID}.entrypoints=websecure"
      - "traefik.http.routers.${CI_PROJECT_ID}.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.${CI_PROJECT_ID}.tls=true"
      - "traefik.http.routers.${CI_PROJECT_ID}.tls.certresolver=lets-encrypt"
      - "traefik.docker.network=traefik"
    volumes:
      - public_link:/var/www/html/public


networks:
  internal:
    driver: bridge
  traefik:
    external: true

volumes:
  storage_link:
    driver: local
  public_link:
    driver: local

